const request = require('supertest');
const app = require('../src/app');
const service = require('../src/services/taskService');
beforeEach(()=>service._reset());
const create = (body={title:'Test task'}) => request(app).post('/tasks').send(body);
describe('Task API',()=>{
 test('GET /tasks returns tasks',async()=>{await create();const r=await request(app).get('/tasks');expect(r.status).toBe(200);expect(r.body).toHaveLength(1);});
 test('GET /tasks filters by status',async()=>{await create({title:'A',status:'todo'});await create({title:'B',status:'done'});const r=await request(app).get('/tasks?status=todo');expect(r.status).toBe(200);expect(r.body).toHaveLength(1);});
 test('GET /tasks paginates page one correctly',async()=>{await create({title:'A'});await create({title:'B'});await create({title:'C'});const r=await request(app).get('/tasks?page=1&limit=2');expect(r.body.map(x=>x.title)).toEqual(['A','B']);});
 test('GET /tasks invalid page falls back to page one',async()=>{await create({title:'A'});const r=await request(app).get('/tasks?page=bad&limit=1');expect(r.status).toBe(200);expect(r.body).toHaveLength(1);});
 test('POST /tasks creates task',async()=>{const r=await create({title:'New',priority:'high'});expect(r.status).toBe(201);expect(r.body.title).toBe('New');});
 test('POST /tasks rejects missing title',async()=>{const r=await request(app).post('/tasks').send({});expect(r.status).toBe(400);});
 test('POST /tasks rejects invalid status',async()=>{const r=await create({title:'A',status:'bad'});expect(r.status).toBe(400);});
 test('POST /tasks rejects invalid priority',async()=>{const r=await create({title:'A',priority:'urgent'});expect(r.status).toBe(400);});
 test('POST /tasks rejects invalid due date',async()=>{const r=await create({title:'A',dueDate:'not-a-date'});expect(r.status).toBe(400);});
 test('PUT /tasks/:id updates task',async()=>{const c=await create();const r=await request(app).put(`/tasks/${c.body.id}`).send({title:'Updated'});expect(r.status).toBe(200);expect(r.body.title).toBe('Updated');});
 test('PUT rejects invalid title',async()=>{const c=await create();const r=await request(app).put(`/tasks/${c.body.id}`).send({title:''});expect(r.status).toBe(400);});
 test('PUT returns 404 for missing task',async()=>{const r=await request(app).put('/tasks/nope').send({title:'X'});expect(r.status).toBe(404);});
 test('DELETE removes task',async()=>{const c=await create();const r=await request(app).delete(`/tasks/${c.body.id}`);expect(r.status).toBe(204);expect((await request(app).get('/tasks')).body).toHaveLength(0);});
 test('DELETE missing task returns 404',async()=>{const r=await request(app).delete('/tasks/nope');expect(r.status).toBe(404);});
 test('complete marks task done and preserves priority',async()=>{const c=await create({title:'A',priority:'high'});const r=await request(app).patch(`/tasks/${c.body.id}/complete`);expect(r.status).toBe(200);expect(r.body.status).toBe('done');expect(r.body.priority).toBe('high');});
 test('complete missing task returns 404',async()=>{const r=await request(app).patch('/tasks/nope/complete');expect(r.status).toBe(404);});
 test('stats returns counts',async()=>{await create({title:'A'});await create({title:'B',status:'done'});const r=await request(app).get('/tasks/stats');expect(r.body.todo).toBe(1);expect(r.body.done).toBe(1);});
 test('assign creates assignee',async()=>{const c=await create();const r=await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:'Kaustub'});expect(r.status).toBe(200);expect(r.body.assignee).toBe('Kaustub');});
 test('assign trims whitespace',async()=>{const c=await create();const r=await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:'  Kaustub  '});expect(r.status).toBe(200);expect(r.body.assignee).toBe('Kaustub');});
 test('assign rejects empty assignee',async()=>{const c=await create();const r=await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:'   '});expect(r.status).toBe(400);});
 test('assign rejects non-string assignee',async()=>{const c=await create();const r=await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:123});expect(r.status).toBe(400);});
 test('assign missing task returns 404',async()=>{const r=await request(app).patch('/tasks/nope/assign').send({assignee:'A'});expect(r.status).toBe(404);});
 test('assigning twice returns 409',async()=>{const c=await create();await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:'A'});const r=await request(app).patch(`/tasks/${c.body.id}/assign`).send({assignee:'B'});expect(r.status).toBe(409);});
});
